
// Button control style and images
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.style.button.css", "text/css", PerformSubstitution = true)]

[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.classic.blue.c.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.classic.blue.l.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.classic.blue.r.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.classic.green.c.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.classic.green.l.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.classic.green.r.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.classic.red.c.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.classic.red.l.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.classic.red.r.png", "img/png")]


[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.blue.l.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.blue.c.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.blue.r.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.blue.lh.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.blue.ch.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.blue.rh.png", "img/png")]

[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.gray.l.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.gray.c.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.gray.r.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.gray.lh.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.gray.ch.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.gray.rh.png", "img/png")]

[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.green.l.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.green.c.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.green.r.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.green.lh.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.green.ch.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.green.rh.png", "img/png")]

[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.pink.l.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.pink.c.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.pink.r.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.pink.lh.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.pink.ch.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.pink.rh.png", "img/png")]

[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.purple.l.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.purple.c.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.purple.r.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.purple.lh.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.purple.ch.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.purple.rh.png", "img/png")]

[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.red.l.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.red.c.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.red.r.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.red.lh.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.red.ch.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.red.rh.png", "img/png")]

[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.yellow.l.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.yellow.c.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.yellow.r.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.yellow.lh.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.yellow.ch.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.fancy.yellow.rh.png", "img/png")]

[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.blue.l.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.blue.c.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.blue.r.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.blue.lh.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.blue.ch.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.blue.rh.png", "img/png")]

[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.gray.l.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.gray.c.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.gray.r.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.gray.lh.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.gray.ch.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.gray.rh.png", "img/png")]

[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.green.l.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.green.c.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.green.r.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.green.lh.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.green.ch.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.green.rh.png", "img/png")]

[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.pink.l.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.pink.c.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.pink.r.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.pink.lh.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.pink.ch.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.pink.rh.png", "img/png")]

[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.purple.l.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.purple.c.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.purple.r.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.purple.lh.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.purple.ch.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.purple.rh.png", "img/png")]

[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.red.l.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.red.c.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.red.r.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.red.lh.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.red.ch.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.red.rh.png", "img/png")]

[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.yellow.l.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.yellow.c.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.yellow.r.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.yellow.lh.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.yellow.ch.png", "img/png")]
[assembly: System.Web.UI.WebResource("RainstormStudios.Web.UI.WebControls.images.button.plastic.yellow.rh.png", "img/png")]
