//  Copyright (c) 2008, Michael unfried
//  Email:  serbius3@gmail.com
//  All rights reserved.

//  Redistribution and use in source and binary forms, with or without modification, 
//  are permitted provided that the following conditions are met:

//  Redistributions of source code must retain the above copyright notice, 
//  this list of conditions and the following disclaimer. 
//  Redistributions in binary form must reproduce the above copyright notice, 
//  this list of conditions and the following disclaimer in the documentation 
//  and/or other materials provided with the distribution. 

//  THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
//  KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
//  IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
//  PURPOSE. IT CAN BE DISTRIBUTED FREE OF CHARGE AS LONG AS THIS HEADER 
//  REMAINS UNCHANGED.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RainstormStudios.Web.UI.WebControls
{
    public class ImageButton : System.Web.UI.WebControls.ImageButton
    {
        #region Properties
        //***************************************************************************
        // Public Properties
        // 
        public string ImageUrlDisabled
        {
            get { return (string)this.ViewState["DisabledImageUrl"]; }
            set { this.ViewState["DisabledImageUrl"] = value; }
        }
        public bool AutoGenerateDisabledImage
        {
            get { return this.ViewState.GetBoolean("AutoGenDisImg", true, false); }
            set { this.ViewState["AutoGenDisImg"] = value; }
        }
        public override string ImageUrl
        {
            get
            {
                if (!this.Enabled)
                {
                    if (this.AutoGenerateDisabledImage)
                    {
                        string imgUrl = this.ImageUrlDisabled;
                        if (!System.Web.VirtualPathUtility.IsAbsolute(imgUrl))
                            imgUrl = System.Web.VirtualPathUtility.ToAbsolute(this.ImageUrlDisabled);
                        return string.Format("rsImageButton.axd?img={0}", System.Web.HttpContext.Current.Server.UrlEncode(imgUrl));
                    }
                    else if (!string.IsNullOrEmpty(this.ImageUrlDisabled))
                        return this.ImageUrlDisabled;
                    else
                        return base.ImageUrl;
                }
                else
                {
                    return base.ImageUrl;
                }
            }
            set
            {
                base.ImageUrl = value;
            }
        }
        #endregion
    }
}